"use client";

import { Festival } from "@/lib/festivals";
import type { Language } from "@/lib/generator";

interface Props {
  message: string;
  festival: Festival;
  language: Language;
}

export default function GreetingCard({ message, festival, language }: Props) {
  const fontClass =
    language === "gujarati"
      ? "font-gujarati"
      : language === "english"
        ? "font-poppins"
        : "font-devanagari";

  return (
    <div className="animate-slide-up">
      <div
        className="relative rounded-2xl sm:rounded-3xl overflow-hidden shadow-xl"
        style={{
          background: `linear-gradient(135deg, ${festival.colors.primary}12, ${festival.colors.secondary}08)`,
        }}
      >
        {/* Top gradient stripe */}
        <div
          className="h-1.5"
          style={{
            background: `linear-gradient(90deg, ${festival.colors.primary}, ${festival.colors.secondary}, ${festival.colors.accent})`,
          }}
        />

        <div className="px-5 py-5 sm:px-8 sm:py-7 space-y-4 sm:space-y-5">
          {/* Festival header */}
          <div className="flex items-center justify-center gap-2">
            <span className="text-3xl sm:text-4xl">{festival.emoji}</span>
            <p
              className="text-xs font-bold uppercase tracking-widest"
              style={{ color: festival.colors.primary }}
            >
              {festival.name}
            </p>
          </div>

          {/* Divider */}
          <div className="flex items-center gap-3">
            <div className="flex-1 h-px" style={{ background: `${festival.colors.primary}25` }} />
            <span className="text-xs" style={{ color: festival.colors.primary }}>✦</span>
            <div className="flex-1 h-px" style={{ background: `${festival.colors.primary}25` }} />
          </div>

          {/* Message */}
          <div
            className={`${fontClass} text-base sm:text-lg leading-relaxed sm:leading-loose text-center text-gray-800 dark:text-gray-100`}
          >
            {message.split("\n").map((line, i) => (
              <p key={i} className={i > 0 ? "mt-2" : ""}>
                {line}
              </p>
            ))}
          </div>

          {/* Footer branding */}
          <p className="text-center text-[10px] text-gray-400 dark:text-gray-500 pt-1">
            Generated by ShubhSandesh ✨
          </p>
        </div>

        {/* Bottom gradient stripe */}
        <div
          className="h-1"
          style={{
            background: `linear-gradient(90deg, ${festival.colors.primary}, ${festival.colors.secondary}, ${festival.colors.accent})`,
          }}
        />
      </div>
    </div>
  );
}
